# -*- coding: utf-8 -*-
"""CIE2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCTlXP7209RgSR3Qz8rQKaS0cdiqEHAw
"""

import pandas as pd
data=pd.read_csv("/content/titanic 4.csv")
print(data)

data.describe()

data.info()

data.head()

data.isnull().sum()

data.duplicated()

import numpy as np
from scipy import stats
mean1=np.mean(data['Age'])
median1=np.median(data['Age'])
mode1=stats.mode(data['Age'],keepdims=True).mode[0]
mean2=np.mean(data['Fare'])
median2=np.median(data['Fare'])
mode2=stats.mode(data['Fare'],keepdims=True).mode[0]
print("Central Tendence")
print("mean Age:",mean1)
print("median Age:",median1)
print("mode:",mode1)
print("mean Fare:",mean2)
print("median Fare:",median2)
print("mode Fare:",mode2)

import pandas as pd
data['Survived']=data['Survived'].replace({1:'survived',0:'not survived'})
print(data['Survived'])

import numpy as np
import matplotlib.pyplot as plt
grouped_data=data.groupby(['Survived','Pclass'])['PassengerId'].count().unstack()
grouped_data.plot(kind='bar')
plt.xlabel('survived')
plt.ylabel('count')
plt.title('categorical variables survived')
plt.xticks(ticks=[0,1],labels=[0,1],rotation=0)
plt.show()

import pandas as pd
ur1='/content/titanic 4.csv'
titanic_data=pd.read_csv(ur1)
print(titanic_data)
null_values=titanic_data.isnull().sum()
titanic_filled_data=titanic_data.fillna(titanic_data.mean(numeric_only=True))
null_values,titanic_filled_data.head()

import pandas as pd
import numpy as np
data = pd.read_csv("/content/titanic 4.csv")

mean = np.mean(data['Age'])
std = np.std(data['Age'])
print('mean of the dataset is', mean)
print('std. deviation is', std)
threshold = 3
outlier = []

for i in data['Age']:
    z = (i-mean)/std
    if z > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

import seaborn as sns
sns.boxplot(data['Age'])
plt.title('Boxplot of Age')
plt.ylabel('Age')
plt.show()